"""initial schema

Revision ID: 889f44355f49
Revises: a3e57d0c7e29
Create Date: 2026-09-14 00:18:13.669012

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "889f44355f49"
down_revision: Union[str, Sequence[str], None] = "a3e57d0c7e29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
