"""initial schema

Revision ID: a3e57d0c7e29
Revises: c097b9abf5ff
Create Date: 2026-09-14 00:16:43.322012

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a3e57d0c7e29"
down_revision: Union[str, Sequence[str], None] = "c097b9abf5ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
